language: node_js
node_js:
  - "0.8"
  - "0.10"
before_install:
  - gem --version
  - gem update --system
# jekyll stuff
  - gem install jekyll
# compass & compass extensions
  - gem install compass
# grunt-webfont requirements
  - sudo apt-get install fontforge eot-utils
  - wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  - unzip woff-code-latest.zip -d sfnt2woff && cd sfnt2woff && make && sudo mv sfnt2woff /usr/local/bin/ && cd ..
  - gem install fontcustom
# grunt
  - npm install -g grunt-cli
  - npm install
# bower
  - export PATH=$PATH:`npm bin` # add local bower
  - bower --version
  - bower install
